// AUTO-GENERATED FILE — do not edit by hand.
// Generated from ORGANIGRAMMA.xlsx at 2025-12-24T08:43:27
//
// Data contract:
// - userId is canonicalized as "COGNOME NOME" uppercase, single-spaced
// - reportsToByUserId expresses the management chain (CONSULENTE -> TEAM_LEADER -> ADMIN)
// - assignedAssistantByOwnerId is OPTIONAL per-consulente affiancatore (no fill-down)
// - globalAssistants are transversal affiancatori with broad scope

export const ORG_META = {
  "generatedAt": "2025-12-24T08:43:27",
  "source": "ORGANIGRAMMA.xlsx",
  "counts": {
    "users": 64,
    "admins": 4,
    "teamLeaders": 6,
    "affiancatori": 3,
    "consulenti": 51,
    "assignedAssistants": 29,
    "globalAssistants": 4
  }
};

export const ROLE_BY_USER_ID = {
  "CACCIOLA GIUSEPPE": "ADMIN",
  "AMENDOLA GIANLUCA": "TEAM_LEADER",
  "GOTI GIOELE": "AFFIANCATORE",
  "BORGHI ALESSANDRO": "CONSULENTE",
  "CAROSELLA MARCO": "ADMIN",
  "CARLONI MARIA CHIARA": "CONSULENTE",
  "GIACOMELLI ALESSIO": "ADMIN",
  "CECCARELLI STEFANIA": "CONSULENTE",
  "PROVENZANO CLAUDIO": "ADMIN",
  "DEIANA ANTONELLO": "CONSULENTE",
  "FRASCARO EMANUELE": "CONSULENTE",
  "MAGGIO LETIZIA": "CONSULENTE",
  "ROSSI CLAUDIA": "CONSULENTE",
  "CASSARA' MATETO": "CONSULENTE",
  "SCURZONI LORENZO": "CONSULENTE",
  "BOGANI FEDERICO": "CONSULENTE",
  "GRIFONI GUIDO GALILEO": "AFFIANCATORE",
  "BENEDETTI MERZIA": "CONSULENTE",
  "BRUNI FRANCESCO": "CONSULENTE",
  "CIOBANOIU TAMARA CRISTINA": "CONSULENTE",
  "FINESCHI ALESSANDRO": "CONSULENTE",
  "GABBIANI EDOARDO": "CONSULENTE",
  "GIOVACCHINI MIRKO": "CONSULENTE",
  "GIUSTI SARA": "CONSULENTE",
  "GJACI DAVA": "CONSULENTE",
  "PETRACCHI VERONICA": "CONSULENTE",
  "TORSELLI FRANCESCO": "CONSULENTE",
  "VALECCHI SAMUELE": "CONSULENTE",
  "MARMORINI SIMONE": "CONSULENTE",
  "NINCHERI MATTEO": "TEAM_LEADER",
  "VAIANI ALBERTO": "AFFIANCATORE",
  "CAMA ANTONIO": "CONSULENTE",
  "BAGNOLI MARCO": "CONSULENTE",
  "CARMIGNANI FABIO": "CONSULENTE",
  "VALLERINI FRANCESCO": "TEAM_LEADER",
  "SCIANNAME' CLAUDIO": "CONSULENTE",
  "CAVAGNA MATTEO": "CONSULENTE",
  "BRUNELLI MATTEO": "CONSULENTE",
  "PIAZZINI SIMONE": "CONSULENTE",
  "FRATONI OLIVIA": "TEAM_LEADER",
  "BERARDONO ELISA MARIA": "CONSULENTE",
  "PIPPA ANDREA": "CONSULENTE",
  "GIGLIOTTI FORTI ALICE": "CONSULENTE",
  "SPERANZA MARIA CECILIA": "CONSULENTE",
  "SETTESOLDI SIMONE": "TEAM_LEADER",
  "TORRE PAMELA": "CONSULENTE",
  "CARDICCHI LUCIA": "CONSULENTE",
  "ERBAGGIO FRANCESCO": "CONSULENTE",
  "FABBRI GIORGIO": "CONSULENTE",
  "PIERATTINI NICOLA": "CONSULENTE",
  "LOMBARDI DAVID": "CONSULENTE",
  "PASQUALETTI SERENELLA": "CONSULENTE",
  "AGENZIA": "TEAM_LEADER",
  "CACCIOLA PAOLO": "CONSULENTE",
  "BONINSEGNI ALBERTO": "CONSULENTE",
  "CAROSELLA FABIANA": "CONSULENTE",
  "CHIANUCCI ANTONELLA": "CONSULENTE",
  "DAINELLI MARIA GRAZIA": "CONSULENTE",
  "MACCIONI STEFANO": "CONSULENTE",
  "MENCATTINI SILVIA": "CONSULENTE",
  "PAPUCCI VERONICA": "CONSULENTE",
  "RAVANOLO KATIA": "CONSULENTE",
  "SESTINI LEONARDO": "CONSULENTE",
  "TONIONI MARZIA": "CONSULENTE"
};

export const REPORTS_TO_BY_USER_ID = {
  "CACCIOLA GIUSEPPE": "AGENZIA",
  "AMENDOLA GIANLUCA": "CACCIOLA GIUSEPPE",
  "BORGHI ALESSANDRO": "AMENDOLA GIANLUCA",
  "CAROSELLA MARCO": "AGENZIA",
  "CARLONI MARIA CHIARA": "AMENDOLA GIANLUCA",
  "GIACOMELLI ALESSIO": "AGENZIA",
  "CECCARELLI STEFANIA": "PROVENZANO CLAUDIO",
  "PROVENZANO CLAUDIO": "PROVENZANO CLAUDIO",
  "DEIANA ANTONELLO": "AMENDOLA GIANLUCA",
  "FRASCARO EMANUELE": "AMENDOLA GIANLUCA",
  "GOTI GIOELE": "AMENDOLA GIANLUCA",
  "MAGGIO LETIZIA": "AMENDOLA GIANLUCA",
  "ROSSI CLAUDIA": "AMENDOLA GIANLUCA",
  "CASSARA' MATETO": "AMENDOLA GIANLUCA",
  "SCURZONI LORENZO": "AMENDOLA GIANLUCA",
  "BOGANI FEDERICO": "AMENDOLA GIANLUCA",
  "BENEDETTI MERZIA": "PROVENZANO CLAUDIO",
  "BRUNI FRANCESCO": "PROVENZANO CLAUDIO",
  "CIOBANOIU TAMARA CRISTINA": "PROVENZANO CLAUDIO",
  "FINESCHI ALESSANDRO": "PROVENZANO CLAUDIO",
  "GABBIANI EDOARDO": "PROVENZANO CLAUDIO",
  "GIOVACCHINI MIRKO": "PROVENZANO CLAUDIO",
  "GIUSTI SARA": "PROVENZANO CLAUDIO",
  "GJACI DAVA": "PROVENZANO CLAUDIO",
  "GRIFONI GUIDO GALILEO": "PROVENZANO CLAUDIO",
  "PETRACCHI VERONICA": "PROVENZANO CLAUDIO",
  "TORSELLI FRANCESCO": "PROVENZANO CLAUDIO",
  "VALECCHI SAMUELE": "PROVENZANO CLAUDIO",
  "MARMORINI SIMONE": "PROVENZANO CLAUDIO",
  "NINCHERI MATTEO": "PROVENZANO CLAUDIO",
  "CAMA ANTONIO": "NINCHERI MATTEO",
  "VAIANI ALBERTO": "NINCHERI MATTEO",
  "BAGNOLI MARCO": "NINCHERI MATTEO",
  "CARMIGNANI FABIO": "NINCHERI MATTEO",
  "VALLERINI FRANCESCO": "PROVENZANO CLAUDIO",
  "SCIANNAME' CLAUDIO": "VALLERINI FRANCESCO",
  "CAVAGNA MATTEO": "VALLERINI FRANCESCO",
  "BRUNELLI MATTEO": "VALLERINI FRANCESCO",
  "PIAZZINI SIMONE": "VALLERINI FRANCESCO",
  "FRATONI OLIVIA": "PROVENZANO CLAUDIO",
  "BERARDONO ELISA MARIA": "FRATONI OLIVIA",
  "PIPPA ANDREA": "FRATONI OLIVIA",
  "GIGLIOTTI FORTI ALICE": "FRATONI OLIVIA",
  "SPERANZA MARIA CECILIA": "FRATONI OLIVIA",
  "SETTESOLDI SIMONE": "PROVENZANO CLAUDIO",
  "TORRE PAMELA": "SETTESOLDI SIMONE",
  "CARDICCHI LUCIA": "SETTESOLDI SIMONE",
  "ERBAGGIO FRANCESCO": "SETTESOLDI SIMONE",
  "FABBRI GIORGIO": "SETTESOLDI SIMONE",
  "PIERATTINI NICOLA": "SETTESOLDI SIMONE",
  "LOMBARDI DAVID": "SETTESOLDI SIMONE",
  "PASQUALETTI SERENELLA": "SETTESOLDI SIMONE",
  "AGENZIA": "PROVENZANO CLAUDIO",
  "CACCIOLA PAOLO": "AGENZIA",
  "BONINSEGNI ALBERTO": "AGENZIA",
  "CAROSELLA FABIANA": "AGENZIA",
  "CHIANUCCI ANTONELLA": "AGENZIA",
  "DAINELLI MARIA GRAZIA": "AGENZIA",
  "MACCIONI STEFANO": "AGENZIA",
  "MENCATTINI SILVIA": "AGENZIA",
  "PAPUCCI VERONICA": "AGENZIA",
  "RAVANOLO KATIA": "AGENZIA",
  "SESTINI LEONARDO": "AGENZIA",
  "TONIONI MARZIA": "AGENZIA"
};

export const ASSIGNED_ASSISTANT_BY_OWNER_ID = {
  "BORGHI ALESSANDRO": "GOTI GIOELE",
  "CARLONI MARIA CHIARA": "GOTI GIOELE",
  "CECCARELLI STEFANIA": "GRIFONI GUIDO GALILEO",
  "DEIANA ANTONELLO": "GOTI GIOELE",
  "FRASCARO EMANUELE": "GOTI GIOELE",
  "GOTI GIOELE": "GOTI GIOELE",
  "MAGGIO LETIZIA": "GOTI GIOELE",
  "ROSSI CLAUDIA": "GOTI GIOELE",
  "CASSARA' MATETO": "GOTI GIOELE",
  "SCURZONI LORENZO": "GOTI GIOELE",
  "BOGANI FEDERICO": "GOTI GIOELE",
  "BENEDETTI MERZIA": "GRIFONI GUIDO GALILEO",
  "BRUNI FRANCESCO": "GRIFONI GUIDO GALILEO",
  "CIOBANOIU TAMARA CRISTINA": "GRIFONI GUIDO GALILEO",
  "FINESCHI ALESSANDRO": "GRIFONI GUIDO GALILEO",
  "GABBIANI EDOARDO": "GRIFONI GUIDO GALILEO",
  "GIOVACCHINI MIRKO": "GRIFONI GUIDO GALILEO",
  "GIUSTI SARA": "GRIFONI GUIDO GALILEO",
  "GJACI DAVA": "GRIFONI GUIDO GALILEO",
  "GRIFONI GUIDO GALILEO": "GRIFONI GUIDO GALILEO",
  "PETRACCHI VERONICA": "GRIFONI GUIDO GALILEO",
  "PROVENZANO CLAUDIO": "GRIFONI GUIDO GALILEO",
  "TORSELLI FRANCESCO": "GRIFONI GUIDO GALILEO",
  "VALECCHI SAMUELE": "GRIFONI GUIDO GALILEO",
  "MARMORINI SIMONE": "GRIFONI GUIDO GALILEO",
  "CAMA ANTONIO": "VAIANI ALBERTO",
  "VAIANI ALBERTO": "VAIANI ALBERTO",
  "BAGNOLI MARCO": "VAIANI ALBERTO",
  "CARMIGNANI FABIO": "VAIANI ALBERTO"
};

export const GLOBAL_ASSISTANTS = [
  "CAROSELLA MARCO",
  "GIACOMELLI ALESSIO",
  "NINCHERI MATTEO",
  "PROVENZANO CLAUDIO"
];

// Optional helpers (pure functions)
export function normalizeUserId(v) {
  return (v ?? "")
    .toString()
    .trim()
    .toUpperCase()
    .replace(/\s+/g, " ")
    .replace(/,+$/g, "");
}

export function roleRank(role) {
  switch (role) {
    case "ADMIN": return 4;
    case "TEAM_LEADER": return 3;
    case "AFFIANCATORE": return 2;
    case "CONSULENTE": return 1;
    default: return 0;
  }
}

export function getRole(userId) {
  return ROLE_BY_USER_ID[normalizeUserId(userId)] || null;
}

export function getManager(userId) {
  const id = normalizeUserId(userId);
  return REPORTS_TO_BY_USER_ID[id] || null;
}

export function isGlobalAssistant(userId) {
  const id = normalizeUserId(userId);
  return GLOBAL_ASSISTANTS.includes(id);
}

export function getAssignedAssistant(ownerId) {
  const id = normalizeUserId(ownerId);
  return ASSIGNED_ASSISTANT_BY_OWNER_ID[id] || null;
}

export const org = {
  reportsToByUserId: REPORTS_TO_BY_USER_ID,
  roleByUserId: ROLE_BY_USER_ID,
  assignedAssistantByOwnerId: ASSIGNED_ASSISTANT_BY_OWNER_ID,
  globalAssistants: GLOBAL_ASSISTANTS
};

